### ISSUE TITLE
issue running demo

### ISSUE THREAD

**Issue by ctwoodwa** [thinktecture-labs/article-gRPC-blazor#1]
Thank you for taking the time to write this article.

After downloading and attempting to run the projects and add a new task,  I'm receiving an issue with the grpc connection.

the error message is:
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: TypeError: Failed to fetch JSException: TypeError: Failed to fetch", DebugException="System.Net.Http.HttpRequestException: TypeError: Failed to fetch")
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: TypeError: Failed to fetch JSException: TypeError: Failed to fetch", DebugException="System.Net.Http.HttpRequestException: TypeError: Failed to fetch")
 ---> System.Net.Http.HttpRequestException: TypeError: Failed to fetch
 ---> TypeError: Failed to fetch
   --- End of inner exception stack trace ---
   at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Http.BrowserHttpHandler.CallFetch(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
   at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|55_0(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
   at Grpc.Net.Client.Web.GrpcWebHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__74[[GrpcToDo.Shared.DTOs.ToDoData, GrpcToDo.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[GrpcToDo.Shared.DTOs.ToDoRequestResponse, GrpcToDo.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   --- End of inner exception stack trace ---
   at ProtoBuf.Grpc.Internal.Reshape.<UnaryTaskAsyncImpl>d__16`2[[GrpcToDo.Shared.DTOs.ToDoData, GrpcToDo.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[GrpcToDo.Shared.DTOs.ToDoRequestResponse, GrpcToDo.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 554
   at GrpcToDo.Client.Components.ToDoItemEditor.AddNewTask(MouseEventArgs e) in C:\Projects\article-gRPC-blazor-main\article-gRPC-blazor-main\GrpcToDo.Client\Components\ToDoItemEditor.razor.cs:line 25
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by patrickjahr** [comment]
Thanks for info. I'll look at it in a reasonable time

**Comment by patrickjahr** [comment]
@ctwoodwa Do you start both projects? Server and Client?
Because the client project is not a hosted project.
